server:
  http:
    addr: 0.0.0.0:8668
    timeout: 1s
  grpc:
    addr: 0.0.0.0:8669
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(192.168.5.51:3306)/lottery_system
    addr: 192.168.5.51:3306
    user: root
    password: "123456"
    dataBase: lottery_system
    maxIdleConn : 2000
    maxOpenConn: 20000
    maxIdleTime: 30

  redis:
    addr: 192.168.5.52:6379
    db: 8
    passWord: "123456"
    read_timeout: 2s
    write_timeout: 2s
micro:
  lb:
    addr: 192.168.5.51:20000
