// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"Seckill-Core/internal/biz"
	"Seckill-Core/internal/conf"
	"Seckill-Core/internal/data"
	"Seckill-Core/internal/interfaces"
	"Seckill-Core/internal/server"
	"Seckill-Core/internal/service"
	"Seckill-Core/internal/task"
	"github.com/go-kratos/kratos/v2"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp
//
//	@Author <a href="https://bitoffer.cn">狂飙训练营</a>
//	@Description: wireApp init kratos application.
//	@param *conf.Server
//	@param *conf.Data
//	@return *kratos.App
//	@return func()
//	@return error
func wireApp(confServer *conf.Server, confData *conf.Data) (*kratos.App, func(), error) {
	db := data.NewDatabase(confData)
	client := data.NewCache(confData)
	dataData := data.NewData(db, client)
	userRepo := data.NewSeckill-CoreRepo(dataData)
	transaction := data.NewTransaction(dataData)
	Seckill-CoreUseCase := biz.NewSeckill-CoreUseCase(userRepo, transaction)
	Seckill-CoreService := service.NewSeckill-CoreService(Seckill-CoreUseCase)
	grpcServer := server.NewGRPCServer(confServer, Seckill-CoreService)
	handler := interfaces.NewHandler(Seckill-CoreService)
	httpServer := server.NewHTTPServer(confServer, handler)
	taskServer := task.NewTaskServer(Seckill-CoreService, confServer)
	app := newApp(grpcServer, httpServer, taskServer)
	return app, func() {
	}, nil
}
